services:
  config-audit:
    build: .
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ${PWD}/env.json:/home/node/app/env.json
    command: "node audit.js"
    container_name: "config-audit"
    image: "config-audit"